version: '3.3'

networks:
  treenet:
    driver: bridge

services:
  translator_api:
    image: us-west1-docker.pkg.dev/treeleaf/nmb-access/truconverterapimaster:latest
    container_name: translator_api
    volumes:
      - ./translator_api_conf/logback.xml:/app/BOOT-INF/classes/logback.xml
      - ./translator_api_conf/application.properties:/app/BOOT-INF/classes/application.properties
    networks:
      - treenet
    ports:
      - '9090:8080'
  docgen_api:
    image: us-west1-docker.pkg.dev/treeleaf/nmb-access/docgenapimaster:latest
    container_name: docgen_api
    volumes:
      - /var/docgen:/var/docgen
      - ./docgen_api_conf/logback.xml:/app/BOOT-INF/classes/logback.xml
      - ./docgen_api_conf/application.properties:/app/BOOT-INF/classes/application.properties
    networks:
      - treenet
    ports:
      - '9999:9000'
    depends_on:
      - translator_api
  docgen_web:
    image: us-west1-docker.pkg.dev/treeleaf/nmb-access/docgenuimaster:latest
    container_name: docgen_web
    volumes:
      - /etc/ssl/:/etc/ssl/
      - ./docgen_ui_conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - treenet
    ports:
      - '8080:8080'
    depends_on:
      - docgen_api
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_URL=http://localhost:9091
