version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.6.0
    ports:
      - '9200:9200'
      - '9300:9300'
  logstash:
    image: logstash:8.6.0
  kibana:
    image: kibana:8.6.0
    ports:
      - '5601:5601'