version: '3.3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'anydone'
      MYSQL_USER: 'anydone'
      MYSQL_PASSWORD: 'nb3?N#tq'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - data:/var/lib/mysql
      - ./sql/export.query.sql:/home/mysql/export.query.sh
      - ./sql/anydone.sql:/home/mysql/anydone.sql
      - ./sql/message.sql:/home/mysql/message.sql
      - ./restore.sh:/home/mysql/restore.sh
# Names our volume
volumes:
  data: